
druid2:
  poolType: com.alibaba.druid.pool.DruidDataSource
  dbs:
    dba:
      mapperLocations: classpath:mybatis/dba/*.xml
      typeHandlersPackage:
      mapperScannerPackage: cn.iwuliao.ds.mapper.dba
#      plugins:
#        - cn.iwuliao.ds.mapper.plugin.MyBatisPlugin

      master:
        url: jdbc:mysql://10.211.55.5:3306/dba?serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: rootroot!123R
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
      slave:
        url: jdbc:mysql://10.211.55.5:3306/dba?serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: rootroot!123R
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
    dbb:
      mapperLocations: classpath:mybatis/dbb/*.xml
      typeHandlersPackage:
      mapperScannerPackage: cn.iwuliao.ds.mapper.dbb
      master:
        url: jdbc:mysql://10.211.55.5:3306/dbb?serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: rootroot!123R
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
      slave:
        url: jdbc:mysql://10.211.55.5:3306/dbb?serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: rootroot!123R
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'

logging:
  level:
    root: info
    cn.iwuliao.ds.mapper: debug