
druid2:
  poolType: com.alibaba.druid.pool.DruidDataSource
  dbs:
    dba:
      mapperLocations: classpath:mybatis/dba/*.xml
      typeHandlersPackage:
      mapperScannerPackage: cn.iwuliao.ds.mapper.dba
      master:
        url: jdbc:mysql://127.0.0.1:3306/dba?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
      slave:
        url: jdbc:mysql://127.0.0.1:3306/dba?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
    dbb:
      mapperLocations: classpath:mybatis/dbb/*.xml
      typeHandlersPackage:
      mapperScannerPackage: cn.iwuliao.ds.mapper.dbb
      master:
        url: jdbc:mysql://127.0.0.1:3306/dbb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'
      slave:
        url: jdbc:mysql://127.0.0.1:3306/dbb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useLocalSessionState=true&autoReconnect=true&failOverReadOnly=false&noAccessToProcedureBodies=true&useTimezone=true&serverTimezone=Hongkong
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        initialSize: '1'
        minIdle: '1'
        maxActive: '20'
        testOnBorrow: 'true'

logging:
  level:
    root: info